"""Time every stage separately, so optimisation targets a measured bottleneck.

Total FPS says the pipeline is slow; it does not say what to fix. This breaks one frame
into its stages and times each one, on a fixed image so the numbers are comparable between
runs (issue #10).

Usage:
    uv run python scripts/bench.py
    uv run python scripts/bench.py --image data/sample.jpg --runs 30
"""

from __future__ import annotations

import argparse
import statistics
import time
from pathlib import Path

import cv2
import numpy as np

from facepipe.align import align_face
from facepipe.arcface import ArcFaceEmbedder
from facepipe.config import DATA_DIR, PROJECT_ROOT
from facepipe.gallery import Gallery
from facepipe.pipeline import annotate, RecognizedFace
from facepipe.scrfd import SCRFDDetector, letterbox, nms, preprocess


def time_it(fn, runs: int) -> tuple[float, float]:
    """Median and standard deviation in ms. Median because an occasional scheduling
    hiccup should not decide which stage looks slowest."""
    samples = []
    for _ in range(runs):
        start = time.perf_counter()
        fn()
        samples.append((time.perf_counter() - start) * 1000)
    return statistics.median(samples), statistics.pstdev(samples)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", default=str(DATA_DIR / "sample.jpg"))
    parser.add_argument("--runs", type=int, default=20)
    parser.add_argument("--write-results", action="store_true")
    args = parser.parse_args()

    frame = cv2.imread(args.image)
    if frame is None:
        raise SystemExit(f"could not read {args.image}")

    detector = SCRFDDetector()
    embedder = ArcFaceEmbedder()
    gallery = Gallery()

    # Set up the inputs each stage needs, so every stage is timed on its own.
    canvas, scale, pad = letterbox(frame)
    blob = preprocess(canvas)
    outputs = detector.session.run(None, {detector.input_name: blob})
    boxes, scores, landmarks = detector._decode(outputs)
    detections = detector.detect(frame)
    if not detections:
        raise SystemExit(f"no face in {args.image}, pick an image with one")
    aligned = align_face(frame, detections[0].kps)
    embedding = embedder.embed(aligned)

    if len(gallery) == 0:
        gallery.add("bench", embedding)

    stages = [
        ("letterbox", lambda: letterbox(frame)),
        ("preprocess", lambda: preprocess(canvas)),
        ("detect (model)", lambda: detector.session.run(None, {detector.input_name: blob})),
        ("decode", lambda: detector._decode(outputs)),
        ("nms", lambda: nms(boxes, scores, 0.4)),
        ("align", lambda: align_face(frame, detections[0].kps)),
        ("embed (model)", lambda: embedder.embed(aligned)),
        ("match", lambda: gallery.match(embedding)),
        (
            "jpeg encode",
            lambda: cv2.imencode(
                ".jpg",
                annotate(frame, [RecognizedFace(detections[0], gallery.match(embedding))]),
                [cv2.IMWRITE_JPEG_QUALITY, 80],
            ),
        ),
    ]

    print(f"{len(detections)} face(s) in {Path(args.image).name}, {args.runs} runs each\n")
    results = []
    for name, fn in stages:
        median, deviation = time_it(fn, args.runs)
        results.append((name, median, deviation))

    total = sum(median for _, median, _ in results)
    lines = [f"{'stage':<16} {'ms':>8} {'+/-':>7} {'share':>7}", "-" * 42]
    for name, median, deviation in results:
        lines.append(f"{name:<16} {median:8.2f} {deviation:7.2f} {median / total:6.1%}")
    lines.append("-" * 42)
    lines.append(f"{'total (1 face)':<16} {total:8.2f} {'':>7} {1000 / total:5.1f} fps")

    model_time = sum(m for n, m, _ in results if "(model)" in n)
    lines.append("")
    lines.append(
        f"the two models are {model_time / total:.0%} of the frame; everything I wrote "
        f"myself is the other {1 - model_time / total:.0%}"
    )
    embed_ms = next(m for n, m, _ in results if n == "embed (model)")
    lines.append(
        f"embedding is per face, so a second person adds {embed_ms:.0f}ms "
        f"({1000 / (total + embed_ms):.1f} fps with 2 faces, "
        f"{1000 / (total + 4 * embed_ms):.1f} with 5)"
    )

    text = "\n".join(lines)
    print(text)

    if args.write_results:
        out = PROJECT_ROOT / "docs" / "results.md"
        existing = out.read_text() if out.exists() else "# Measured results\n"
        marker = "## Per-stage timing (issue #10)"
        block = (
            f"{marker}\n\nOne 640x480 frame with one face, CPU, median of "
            f"{args.runs} runs. Generated by `scripts/bench.py`.\n\n```\n{text}\n```\n"
        )
        if marker in existing:
            existing = existing.split(marker)[0].rstrip() + "\n\n"
        out.write_text(existing.rstrip() + "\n\n" + block)
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
